<section class="page-section Blog-page page-section-41">
        <div class="row menu-row">
            <div class="large-1 go-back">
                <i class="fa-arrow-left fa icon-x back" onclick="window.history.back()"></i>
            </div>
            <div class="large-7 columns p-l-0">
                <h2>
                    Blog
                </h2>
            </div>
            <div class="large-4 columns menu-button text-right">
                <a class="showMenu" href="index.html#home"><i class="fa-home fa icon-x back"></i></a>
                <a class="showMenu"><i class="fa-bars fa icon-x back"></i></a>
                <a class="showMenu"><i class="fa-search fa icon-x back"></i></a>
            </div>
        </div>
        <div class="row clear-fix">
            <div class="row  blog-page">
                <div class="view view-blog view-id-blog view-display-id-block view-dom-id-0c4bf026824ced108c3a32120e9abc56">
                    <div class="view-content">
                        <!-- Poste -->
                        <ul id="i-scroll" class="small-block-grid-1 large-block-grid-3">
                            <?php if( $this->isAllowed('KryuuBlog','add')): ?>
                                <?php echo $this->viewBlogPostPreview(array('add'=>TRUE)); ?>
                            <?php endif; ?>
                            <?php foreach( $this->posts as $post ): ?>
                                <li class="">    
                                <?= $this->viewBlogPostPreview($post); ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="more-link"></div>
                </div>
            </div>
        </div>
    </section>