<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $post) : // <-- change here! ?>
        <tr>
            <td><?php echo $this->escapeHtml($post->title);?></td>
            <td><?php echo $this->escapeHtml($post->author);?></td>
            <td>
                <a href="<?php echo $this->url('KryuuBlog/Edit',
                    array('id' => $post->id));?>">Edit</a>
                <a href="<?php echo $this->url('KryuuBlog/Delete',
                    array('id' => $post->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
    
<?php // add at the end of the file after the table
    echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'KryuuBlog/Admin'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'KryuuBlog/Admin'
    )
);
?>